name: Packer Custom Image Build and Deploy

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Dev credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1

      - name: Install Packer
        uses: hashicorp/setup-packer@v2.0.0

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "adopt"

      - name: Build with Maven
        env:
          DB_USERNAME: ${{secrets.DB_USERNAME}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
        run: mvn clean install -DskipTests

      - name: Run tests
        run: mvn test

      - name: Build Packer Image
        working-directory: PKR
        env:
          PACKER_LOG: 1
          AWS_DEV_ACCOUNT: ${{secrets.AWS_DEV_ACCOUNT}}
          AWS_DEMO_ACCOUNT: ${{secrets.AWS_DEMO_ACCOUNT}}
        run: |
          AMI_USERS_JSON="[\"$(echo ${{secrets.AMI_USERS}} | sed 's/,/\",\"/g')\"]"
          
          packer init .
          packer validate -var="aws_region=us-east-1" \
            -var="subnet_id=${{secrets.SUBNET_ID}}" \
            -var="ami_users=$AMI_USERS_JSON" \
            .
          packer build -var="aws_region=us-east-1" \
            -var="subnet_id=${{secrets.SUBNET_ID}}" \
            -var="ami_users=$AMI_USERS_JSON" \
            .
          AMI_ID=$(aws ec2 describe-images \
            --owners $AWS_DEV_ACCOUNT $AWS_DEMO_ACCOUNT \
            --query 'sort_by(Images, &CreationDate)[-1].ImageId' \
            --output text)
          echo "AMI_ID=${AMI_ID}" >> $GITHUB_ENV

      - name: Configure AWS Demo Account credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.DEMO_AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.DEMO_AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1

      - name: Update Demo Infrastructure
        env:
          LAUNCH_TEMPLATE_NAME: "csye6225_asg_launch_template"
          ASG_NAME: "csye6225-asg"
        run: |
          echo "Looking up Launch Template in Demo environment..."
          
          LAUNCH_TEMPLATE_ID=$(aws ec2 describe-launch-templates \
            --filters "Name=launch-template-name,Values=$LAUNCH_TEMPLATE_NAME" \
            --query 'LaunchTemplates[0].LaunchTemplateId' \
            --output text)
          
          if [ "$LAUNCH_TEMPLATE_ID" = "None" ] || [ -z "$LAUNCH_TEMPLATE_ID" ]; then
            echo "Error: Failed to find launch template: $LAUNCH_TEMPLATE_NAME"
            exit 1
          fi
          echo "Found Launch Template ID: $LAUNCH_TEMPLATE_ID"
          
          CURRENT_VERSION=$(aws ec2 describe-launch-templates \
            --launch-template-id $LAUNCH_TEMPLATE_ID \
            --query 'LaunchTemplates[0].LatestVersionNumber' \
            --output text)
          echo "Current template version: $CURRENT_VERSION"
          
          echo "Creating new launch template version with AMI: ${{ env.AMI_ID }}"
          NEW_VERSION=$(aws ec2 create-launch-template-version \
            --launch-template-id $LAUNCH_TEMPLATE_ID \
            --source-version $CURRENT_VERSION \
            --launch-template-data "{\"ImageId\":\"${{ env.AMI_ID }}\"}" \
            --query 'LaunchTemplateVersion.VersionNumber' \
            --output text)
          echo "Created new version: $NEW_VERSION"
          
          echo "Verifying Demo Auto Scaling Group..."
          ASG_CHECK=$(aws autoscaling describe-auto-scaling-groups \
            --auto-scaling-group-names "$ASG_NAME" \
            --query 'length(AutoScalingGroups)' \
            --output text)
          
          if [ "$ASG_CHECK" = "0" ]; then
            echo "Error: Auto Scaling Group $ASG_NAME not found"
            exit 1
          fi
          
          echo "Updating Auto Scaling Group with new launch template version..."
          aws autoscaling update-auto-scaling-group \
            --auto-scaling-group-name "$ASG_NAME" \
            --launch-template LaunchTemplateId=$LAUNCH_TEMPLATE_ID,Version=$NEW_VERSION
          
          echo "Starting instance refresh..."
          REFRESH_ID=$(aws autoscaling start-instance-refresh \
            --auto-scaling-group-name "$ASG_NAME" \
            --preferences '{"MinHealthyPercentage": 90, "InstanceWarmup": 300}' \
            --query 'InstanceRefreshId' \
            --output text)
          
          echo "Monitoring instance refresh..."
          while true; do
            STATUS=$(aws autoscaling describe-instance-refreshes \
              --auto-scaling-group-name "$ASG_NAME" \
              --instance-refresh-ids $REFRESH_ID \
              --query 'InstanceRefreshes[0].Status' \
              --output text)
            
            echo "Instance refresh status: $STATUS"
            if [ "$STATUS" = "Successful" ]; then
              echo "Instance refresh completed successfully"
              exit 0
            elif [ "$STATUS" = "Failed" ] || [ "$STATUS" = "Cancelled" ]; then
              echo "Instance refresh failed or was cancelled"
              exit 1
            fi
            
            echo "Waiting for refresh to complete..."
            sleep 30
          done
